name: G GSI Porter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Configuring environment
         run: |
            git config --global user.name RahulPalXDA
            git config --global user.email RahulPal.XDA@gmail.com
            git config --global core.editor nano
            sudo -E apt-get -qq install xz-utils unzip gzip tar wget curl

       - name: Downloading System & getting system.img.
         run: |
             mkdir Working && cd Working
             curl https://raw.githubusercontent.com/chashmishani/AniPorter/main/config.txt >> port.sh
             curl https://raw.githubusercontent.com/chashmishani/Port_Script/main/main.sh >> port.sh
             chmod 777 port.sh
             ./port.sh

       - name: Uploading Rom.
         run: |
             cat ~/upload.txt
